# -*- coding: utf-8 -*-
"""Numpy_Basic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/179ylBU9DjK98N0PDbOKkBkdv58TRKqfh
"""

!pip install numpy

import numpy as np

lst = [1,5,9,6,10]

arra = np.array(lst)
print("Numpy Array: \n{}".format(arra))



print("Datatype of array's element: {}".format(arra.dtype))

print("Type of array: {}".format(type(arra)))

print("Dimension of array: {}".format(arra.ndim))

print("Shape of array: {}".format(arra.shape))

print("Size of array: {}".format(arra.size))

ones =np.ones((3,5),dtype = int)
print("Ones Array: \n{}".format(ones))
print("\nDimesion of array: {}".format((ones.ndim)))
print("\nShape of array: {}".format((ones.shape)))
print("\nDatatype of array's Element: {}".format((ones.dtype)))
print("\nTypes of array: {}".format(type(ones)))
print("\nElements no in Array: {}".format((ones.size)))

ones = np.zeros((6,7),dtype = float)
print("Ones Array: \n{}".format(ones))
print("\nDimesion of array: {}".format((ones.ndim)))
print("\nShape of array: {}".format((ones.shape)))
print("\nDatatype of array's Element: {}".format((ones.dtype)))
print("\nTypes of array: {}".format(type(ones)))
print("\nElements no in Array: {}".format((ones.size)))

